name: Prevent docs merge

on:
  pull_request:
    branches:
      - master

jobs:
  prevent-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "master" && "${{ github.event.pull_request.head.ref }}" == "docs" ]]; then
            echo "Merging docs into master is not allowed."
            exit 1
          fi